[config]
schemaVersion = "0.0.1"

[package]
namespace = "jg224"
name = "CraftIndex"
versionNumber = "0.3.0"
description = "Organizes Valheim's Hammer and crafting-station menus."
websiteUrl = "https://github.com/jg224/CraftIndex"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2333"

[build]
icon = "./thunderstore/icon.png"
readme = "./thunderstore/README.md"
outdir = "./dist/thunderstore"

[[build.copy]]
source = "./src/InventoryUX/bin/Release/net472/CraftIndex.dll"
target = "CraftIndex.dll"

[[build.copy]]
source = "./LICENSE"
target = "LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]

[publish.categories]
valheim = [ "mods", "tweaks", "crafting", "client-side", "utility" ]
